# ColQuery (edge) settings
colquery.bind.ip=0.0.0.0
colquery.local.ip=127.0.0.1
colquery.remote.ip=127.0.0.1
colquery.local.rpc.port=9090
colquery.remote.rpc.port=9091
colquery.local.mpp.port=10740
colquery.remote.mpp.port=10744
colquery.col.query.wait=2
colquery.iscol.query=false
#colquery.iscol.query=true

