# ColQuery (cloud) settings
colquery.bind.ip=0.0.0.0
colquery.local.ip=127.0.0.1
colquery.remote.ip=127.0.0.1
colquery.local.rpc.port=9091
colquery.remote.rpc.port=9090
colquery.local.mpp.port=10744
colquery.remote.mpp.port=10740

