/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.iotdb.db.queryengine.execution.colquery.colservice;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2025-08-29")
public class ColumnData extends org.apache.thrift.TUnion<ColumnData, ColumnData._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ColumnData");
  private static final org.apache.thrift.protocol.TField INT_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("intValues", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField LONG_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("longValues", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField DOUBLE_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("doubleValues", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField STRING_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("stringValues", org.apache.thrift.protocol.TType.LIST, (short)4);
  private static final org.apache.thrift.protocol.TField BOOL_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("boolValues", org.apache.thrift.protocol.TType.LIST, (short)5);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    INT_VALUES((short)1, "intValues"),
    LONG_VALUES((short)2, "longValues"),
    DOUBLE_VALUES((short)3, "doubleValues"),
    STRING_VALUES((short)4, "stringValues"),
    BOOL_VALUES((short)5, "boolValues");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INT_VALUES
          return INT_VALUES;
        case 2: // LONG_VALUES
          return LONG_VALUES;
        case 3: // DOUBLE_VALUES
          return DOUBLE_VALUES;
        case 4: // STRING_VALUES
          return STRING_VALUES;
        case 5: // BOOL_VALUES
          return BOOL_VALUES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INT_VALUES, new org.apache.thrift.meta_data.FieldMetaData("intValues", org.apache.thrift.TFieldRequirementType.OPTIONAL,
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
                    new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    tmpMap.put(_Fields.LONG_VALUES, new org.apache.thrift.meta_data.FieldMetaData("longValues", org.apache.thrift.TFieldRequirementType.OPTIONAL,
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
                    new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))));
    tmpMap.put(_Fields.DOUBLE_VALUES, new org.apache.thrift.meta_data.FieldMetaData("doubleValues", org.apache.thrift.TFieldRequirementType.OPTIONAL,
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
                    new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE))));
    tmpMap.put(_Fields.STRING_VALUES, new org.apache.thrift.meta_data.FieldMetaData("stringValues", org.apache.thrift.TFieldRequirementType.OPTIONAL,
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
                    new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.BOOL_VALUES, new org.apache.thrift.meta_data.FieldMetaData("boolValues", org.apache.thrift.TFieldRequirementType.OPTIONAL,
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
                    new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ColumnData.class, metaDataMap);
  }

  public ColumnData() {
    super();
  }

  public ColumnData(_Fields setField, Object value) {
    super(setField, value);
  }

  public ColumnData(ColumnData other) {
    super(other);
  }
  public ColumnData deepCopy() {
    return new ColumnData(this);
  }

  public static ColumnData intValues(java.util.List<Integer> value) {
    ColumnData x = new ColumnData();
    x.setIntValues(value);
    return x;
  }

  public static ColumnData longValues(java.util.List<Long> value) {
    ColumnData x = new ColumnData();
    x.setLongValues(value);
    return x;
  }

  public static ColumnData doubleValues(java.util.List<Double> value) {
    ColumnData x = new ColumnData();
    x.setDoubleValues(value);
    return x;
  }

  public static ColumnData stringValues(java.util.List<String> value) {
    ColumnData x = new ColumnData();
    x.setStringValues(value);
    return x;
  }

  public static ColumnData boolValues(java.util.List<Boolean> value) {
    ColumnData x = new ColumnData();
    x.setBoolValues(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case INT_VALUES:
        if (value instanceof java.util.List) {
          break;
        }
        throw new ClassCastException("Was expecting value of type java.util.List<java.lang.Integer> for field 'intValues', but got " + value.getClass().getSimpleName());
      case LONG_VALUES:
        if (value instanceof java.util.List) {
          break;
        }
        throw new ClassCastException("Was expecting value of type java.util.List<java.lang.Long> for field 'longValues', but got " + value.getClass().getSimpleName());
      case DOUBLE_VALUES:
        if (value instanceof java.util.List) {
          break;
        }
        throw new ClassCastException("Was expecting value of type java.util.List<java.lang.Double> for field 'doubleValues', but got " + value.getClass().getSimpleName());
      case STRING_VALUES:
        if (value instanceof java.util.List) {
          break;
        }
        throw new ClassCastException("Was expecting value of type java.util.List<java.lang.String> for field 'stringValues', but got " + value.getClass().getSimpleName());
      case BOOL_VALUES:
        if (value instanceof java.util.List) {
          break;
        }
        throw new ClassCastException("Was expecting value of type java.util.List<java.lang.Boolean> for field 'boolValues', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case INT_VALUES:
          if (field.type == INT_VALUES_FIELD_DESC.type) {
            java.util.List<Integer> intValues;
            {
              org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
              intValues = new java.util.ArrayList<Integer>(_list8.size);
              int _elem9;
              for (int _i10 = 0; _i10 < _list8.size; ++_i10)
              {
                _elem9 = iprot.readI32();
                intValues.add(_elem9);
              }
              iprot.readListEnd();
            }
            return intValues;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case LONG_VALUES:
          if (field.type == LONG_VALUES_FIELD_DESC.type) {
            java.util.List<Long> longValues;
            {
              org.apache.thrift.protocol.TList _list11 = iprot.readListBegin();
              longValues = new java.util.ArrayList<Long>(_list11.size);
              long _elem12;
              for (int _i13 = 0; _i13 < _list11.size; ++_i13)
              {
                _elem12 = iprot.readI64();
                longValues.add(_elem12);
              }
              iprot.readListEnd();
            }
            return longValues;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case DOUBLE_VALUES:
          if (field.type == DOUBLE_VALUES_FIELD_DESC.type) {
            java.util.List<Double> doubleValues;
            {
              org.apache.thrift.protocol.TList _list14 = iprot.readListBegin();
              doubleValues = new java.util.ArrayList<Double>(_list14.size);
              double _elem15;
              for (int _i16 = 0; _i16 < _list14.size; ++_i16)
              {
                _elem15 = iprot.readDouble();
                doubleValues.add(_elem15);
              }
              iprot.readListEnd();
            }
            return doubleValues;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case STRING_VALUES:
          if (field.type == STRING_VALUES_FIELD_DESC.type) {
            java.util.List<String> stringValues;
            {
              org.apache.thrift.protocol.TList _list17 = iprot.readListBegin();
              stringValues = new java.util.ArrayList<String>(_list17.size);
              @org.apache.thrift.annotation.Nullable String _elem18;
              for (int _i19 = 0; _i19 < _list17.size; ++_i19)
              {
                _elem18 = iprot.readString();
                stringValues.add(_elem18);
              }
              iprot.readListEnd();
            }
            return stringValues;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case BOOL_VALUES:
          if (field.type == BOOL_VALUES_FIELD_DESC.type) {
            java.util.List<Boolean> boolValues;
            {
              org.apache.thrift.protocol.TList _list20 = iprot.readListBegin();
              boolValues = new java.util.ArrayList<Boolean>(_list20.size);
              boolean _elem21;
              for (int _i22 = 0; _i22 < _list20.size; ++_i22)
              {
                _elem21 = iprot.readBool();
                boolValues.add(_elem21);
              }
              iprot.readListEnd();
            }
            return boolValues;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case INT_VALUES:
        java.util.List<Integer> intValues = (java.util.List<Integer>)value_;
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, intValues.size()));
        for (int _iter23 : intValues)
        {
          oprot.writeI32(_iter23);
        }
        oprot.writeListEnd();
      }
      return;
      case LONG_VALUES:
        java.util.List<Long> longValues = (java.util.List<Long>)value_;
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, longValues.size()));
        for (long _iter24 : longValues)
        {
          oprot.writeI64(_iter24);
        }
        oprot.writeListEnd();
      }
      return;
      case DOUBLE_VALUES:
        java.util.List<Double> doubleValues = (java.util.List<Double>)value_;
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, doubleValues.size()));
        for (double _iter25 : doubleValues)
        {
          oprot.writeDouble(_iter25);
        }
        oprot.writeListEnd();
      }
      return;
      case STRING_VALUES:
        java.util.List<String> stringValues = (java.util.List<String>)value_;
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, stringValues.size()));
        for (String _iter26 : stringValues)
        {
          oprot.writeString(_iter26);
        }
        oprot.writeListEnd();
      }
      return;
      case BOOL_VALUES:
        java.util.List<Boolean> boolValues = (java.util.List<Boolean>)value_;
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.BOOL, boolValues.size()));
        for (boolean _iter27 : boolValues)
        {
          oprot.writeBool(_iter27);
        }
        oprot.writeListEnd();
      }
      return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case INT_VALUES:
          java.util.List<Integer> intValues;
        {
          org.apache.thrift.protocol.TList _list28 = iprot.readListBegin();
          intValues = new java.util.ArrayList<Integer>(_list28.size);
          int _elem29;
          for (int _i30 = 0; _i30 < _list28.size; ++_i30)
          {
            _elem29 = iprot.readI32();
            intValues.add(_elem29);
          }
          iprot.readListEnd();
        }
        return intValues;
        case LONG_VALUES:
          java.util.List<Long> longValues;
        {
          org.apache.thrift.protocol.TList _list31 = iprot.readListBegin();
          longValues = new java.util.ArrayList<Long>(_list31.size);
          long _elem32;
          for (int _i33 = 0; _i33 < _list31.size; ++_i33)
          {
            _elem32 = iprot.readI64();
            longValues.add(_elem32);
          }
          iprot.readListEnd();
        }
        return longValues;
        case DOUBLE_VALUES:
          java.util.List<Double> doubleValues;
        {
          org.apache.thrift.protocol.TList _list34 = iprot.readListBegin();
          doubleValues = new java.util.ArrayList<Double>(_list34.size);
          double _elem35;
          for (int _i36 = 0; _i36 < _list34.size; ++_i36)
          {
            _elem35 = iprot.readDouble();
            doubleValues.add(_elem35);
          }
          iprot.readListEnd();
        }
        return doubleValues;
        case STRING_VALUES:
          java.util.List<String> stringValues;
        {
          org.apache.thrift.protocol.TList _list37 = iprot.readListBegin();
          stringValues = new java.util.ArrayList<String>(_list37.size);
          @org.apache.thrift.annotation.Nullable String _elem38;
          for (int _i39 = 0; _i39 < _list37.size; ++_i39)
          {
            _elem38 = iprot.readString();
            stringValues.add(_elem38);
          }
          iprot.readListEnd();
        }
        return stringValues;
        case BOOL_VALUES:
          java.util.List<Boolean> boolValues;
        {
          org.apache.thrift.protocol.TList _list40 = iprot.readListBegin();
          boolValues = new java.util.ArrayList<Boolean>(_list40.size);
          boolean _elem41;
          for (int _i42 = 0; _i42 < _list40.size; ++_i42)
          {
            _elem41 = iprot.readBool();
            boolValues.add(_elem41);
          }
          iprot.readListEnd();
        }
        return boolValues;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new org.apache.thrift.protocol.TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case INT_VALUES:
        java.util.List<Integer> intValues = (java.util.List<Integer>)value_;
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, intValues.size()));
        for (int _iter43 : intValues)
        {
          oprot.writeI32(_iter43);
        }
        oprot.writeListEnd();
      }
      return;
      case LONG_VALUES:
        java.util.List<Long> longValues = (java.util.List<Long>)value_;
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, longValues.size()));
        for (long _iter44 : longValues)
        {
          oprot.writeI64(_iter44);
        }
        oprot.writeListEnd();
      }
      return;
      case DOUBLE_VALUES:
        java.util.List<Double> doubleValues = (java.util.List<Double>)value_;
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, doubleValues.size()));
        for (double _iter45 : doubleValues)
        {
          oprot.writeDouble(_iter45);
        }
        oprot.writeListEnd();
      }
      return;
      case STRING_VALUES:
        java.util.List<String> stringValues = (java.util.List<String>)value_;
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, stringValues.size()));
        for (String _iter46 : stringValues)
        {
          oprot.writeString(_iter46);
        }
        oprot.writeListEnd();
      }
      return;
      case BOOL_VALUES:
        java.util.List<Boolean> boolValues = (java.util.List<Boolean>)value_;
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.BOOL, boolValues.size()));
        for (boolean _iter47 : boolValues)
        {
          oprot.writeBool(_iter47);
        }
        oprot.writeListEnd();
      }
      return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case INT_VALUES:
        return INT_VALUES_FIELD_DESC;
      case LONG_VALUES:
        return LONG_VALUES_FIELD_DESC;
      case DOUBLE_VALUES:
        return DOUBLE_VALUES_FIELD_DESC;
      case STRING_VALUES:
        return STRING_VALUES_FIELD_DESC;
      case BOOL_VALUES:
        return BOOL_VALUES_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public java.util.List<Integer> getIntValues() {
    if (getSetField() == _Fields.INT_VALUES) {
      return (java.util.List<Integer>)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'intValues' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setIntValues(java.util.List<Integer> value) {
    setField_ = _Fields.INT_VALUES;
    value_ = java.util.Objects.requireNonNull(value,"_Fields.INT_VALUES");
  }

  public java.util.List<Long> getLongValues() {
    if (getSetField() == _Fields.LONG_VALUES) {
      return (java.util.List<Long>)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'longValues' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setLongValues(java.util.List<Long> value) {
    setField_ = _Fields.LONG_VALUES;
    value_ = java.util.Objects.requireNonNull(value,"_Fields.LONG_VALUES");
  }

  public java.util.List<Double> getDoubleValues() {
    if (getSetField() == _Fields.DOUBLE_VALUES) {
      return (java.util.List<Double>)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'doubleValues' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setDoubleValues(java.util.List<Double> value) {
    setField_ = _Fields.DOUBLE_VALUES;
    value_ = java.util.Objects.requireNonNull(value,"_Fields.DOUBLE_VALUES");
  }

  public java.util.List<String> getStringValues() {
    if (getSetField() == _Fields.STRING_VALUES) {
      return (java.util.List<String>)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'stringValues' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setStringValues(java.util.List<String> value) {
    setField_ = _Fields.STRING_VALUES;
    value_ = java.util.Objects.requireNonNull(value,"_Fields.STRING_VALUES");
  }

  public java.util.List<Boolean> getBoolValues() {
    if (getSetField() == _Fields.BOOL_VALUES) {
      return (java.util.List<Boolean>)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'boolValues' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setBoolValues(java.util.List<Boolean> value) {
    setField_ = _Fields.BOOL_VALUES;
    value_ = java.util.Objects.requireNonNull(value,"_Fields.BOOL_VALUES");
  }

  public boolean isSetIntValues() {
    return setField_ == _Fields.INT_VALUES;
  }


  public boolean isSetLongValues() {
    return setField_ == _Fields.LONG_VALUES;
  }


  public boolean isSetDoubleValues() {
    return setField_ == _Fields.DOUBLE_VALUES;
  }


  public boolean isSetStringValues() {
    return setField_ == _Fields.STRING_VALUES;
  }


  public boolean isSetBoolValues() {
    return setField_ == _Fields.BOOL_VALUES;
  }


  public boolean equals(Object other) {
    if (other instanceof ColumnData) {
      return equals((ColumnData)other);
    } else {
      return false;
    }
  }

  public boolean equals(ColumnData other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(ColumnData other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    java.util.List<Object> list = new java.util.ArrayList<Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
