/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.iotdb.db.queryengine.execution.colquery.colservice;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2025-08-29")
public class ScanInfo implements org.apache.thrift.TBase<ScanInfo, ScanInfo._Fields>, java.io.Serializable, Cloneable, Comparable<ScanInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ScanInfo");

  private static final org.apache.thrift.protocol.TField OFFSET_FIELD_DESC = new org.apache.thrift.protocol.TField("offset", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField SERIES_PATH_FIELD_DESC = new org.apache.thrift.protocol.TField("seriesPath", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField IS_CLOUD_EQUAL_FIELD_DESC = new org.apache.thrift.protocol.TField("isCloudEqual", org.apache.thrift.protocol.TType.BOOL, (short)3);
  private static final org.apache.thrift.protocol.TField IS_INNER_JOIN_FIELD_DESC = new org.apache.thrift.protocol.TField("isInnerJoin", org.apache.thrift.protocol.TType.BOOL, (short)4);
  private static final org.apache.thrift.protocol.TField IS_FULL_OUTER_JOIN_FIELD_DESC = new org.apache.thrift.protocol.TField("isFullOuterJoin", org.apache.thrift.protocol.TType.BOOL, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ScanInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ScanInfoTupleSchemeFactory();

  public long offset; // required
  public @org.apache.thrift.annotation.Nullable String seriesPath; // required
  public boolean isCloudEqual; // required
  public boolean isInnerJoin; // required
  public boolean isFullOuterJoin; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    OFFSET((short)1, "offset"),
    SERIES_PATH((short)2, "seriesPath"),
    IS_CLOUD_EQUAL((short)3, "isCloudEqual"),
    IS_INNER_JOIN((short)4, "isInnerJoin"),
    IS_FULL_OUTER_JOIN((short)5, "isFullOuterJoin");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // OFFSET
          return OFFSET;
        case 2: // SERIES_PATH
          return SERIES_PATH;
        case 3: // IS_CLOUD_EQUAL
          return IS_CLOUD_EQUAL;
        case 4: // IS_INNER_JOIN
          return IS_INNER_JOIN;
        case 5: // IS_FULL_OUTER_JOIN
          return IS_FULL_OUTER_JOIN;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __OFFSET_ISSET_ID = 0;
  private static final int __ISCLOUDEQUAL_ISSET_ID = 1;
  private static final int __ISINNERJOIN_ISSET_ID = 2;
  private static final int __ISFULLOUTERJOIN_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.OFFSET, new org.apache.thrift.meta_data.FieldMetaData("offset", org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.SERIES_PATH, new org.apache.thrift.meta_data.FieldMetaData("seriesPath", org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IS_CLOUD_EQUAL, new org.apache.thrift.meta_data.FieldMetaData("isCloudEqual", org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.IS_INNER_JOIN, new org.apache.thrift.meta_data.FieldMetaData("isInnerJoin", org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.IS_FULL_OUTER_JOIN, new org.apache.thrift.meta_data.FieldMetaData("isFullOuterJoin", org.apache.thrift.TFieldRequirementType.DEFAULT,
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ScanInfo.class, metaDataMap);
  }

  public ScanInfo() {
  }

  public ScanInfo(
          long offset,
          String seriesPath,
          boolean isCloudEqual,
          boolean isInnerJoin,
          boolean isFullOuterJoin)
  {
    this();
    this.offset = offset;
    setOffsetIsSet(true);
    this.seriesPath = seriesPath;
    this.isCloudEqual = isCloudEqual;
    setIsCloudEqualIsSet(true);
    this.isInnerJoin = isInnerJoin;
    setIsInnerJoinIsSet(true);
    this.isFullOuterJoin = isFullOuterJoin;
    setIsFullOuterJoinIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ScanInfo(ScanInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.offset = other.offset;
    if (other.isSetSeriesPath()) {
      this.seriesPath = other.seriesPath;
    }
    this.isCloudEqual = other.isCloudEqual;
    this.isInnerJoin = other.isInnerJoin;
    this.isFullOuterJoin = other.isFullOuterJoin;
  }

  public ScanInfo deepCopy() {
    return new ScanInfo(this);
  }

  @Override
  public void clear() {
    setOffsetIsSet(false);
    this.offset = 0;
    this.seriesPath = null;
    setIsCloudEqualIsSet(false);
    this.isCloudEqual = false;
    setIsInnerJoinIsSet(false);
    this.isInnerJoin = false;
    setIsFullOuterJoinIsSet(false);
    this.isFullOuterJoin = false;
  }

  public long getOffset() {
    return this.offset;
  }

  public ScanInfo setOffset(long offset) {
    this.offset = offset;
    setOffsetIsSet(true);
    return this;
  }

  public void unsetOffset() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __OFFSET_ISSET_ID);
  }

  /** Returns true if field offset is set (has been assigned a value) and false otherwise */
  public boolean isSetOffset() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __OFFSET_ISSET_ID);
  }

  public void setOffsetIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __OFFSET_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public String getSeriesPath() {
    return this.seriesPath;
  }

  public ScanInfo setSeriesPath(@org.apache.thrift.annotation.Nullable String seriesPath) {
    this.seriesPath = seriesPath;
    return this;
  }

  public void unsetSeriesPath() {
    this.seriesPath = null;
  }

  /** Returns true if field seriesPath is set (has been assigned a value) and false otherwise */
  public boolean isSetSeriesPath() {
    return this.seriesPath != null;
  }

  public void setSeriesPathIsSet(boolean value) {
    if (!value) {
      this.seriesPath = null;
    }
  }

  public boolean isIsCloudEqual() {
    return this.isCloudEqual;
  }

  public ScanInfo setIsCloudEqual(boolean isCloudEqual) {
    this.isCloudEqual = isCloudEqual;
    setIsCloudEqualIsSet(true);
    return this;
  }

  public void unsetIsCloudEqual() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ISCLOUDEQUAL_ISSET_ID);
  }

  /** Returns true if field isCloudEqual is set (has been assigned a value) and false otherwise */
  public boolean isSetIsCloudEqual() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ISCLOUDEQUAL_ISSET_ID);
  }

  public void setIsCloudEqualIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ISCLOUDEQUAL_ISSET_ID, value);
  }

  public boolean isIsInnerJoin() {
    return this.isInnerJoin;
  }

  public ScanInfo setIsInnerJoin(boolean isInnerJoin) {
    this.isInnerJoin = isInnerJoin;
    setIsInnerJoinIsSet(true);
    return this;
  }

  public void unsetIsInnerJoin() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ISINNERJOIN_ISSET_ID);
  }

  /** Returns true if field isInnerJoin is set (has been assigned a value) and false otherwise */
  public boolean isSetIsInnerJoin() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ISINNERJOIN_ISSET_ID);
  }

  public void setIsInnerJoinIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ISINNERJOIN_ISSET_ID, value);
  }

  public boolean isIsFullOuterJoin() {
    return this.isFullOuterJoin;
  }

  public ScanInfo setIsFullOuterJoin(boolean isFullOuterJoin) {
    this.isFullOuterJoin = isFullOuterJoin;
    setIsFullOuterJoinIsSet(true);
    return this;
  }

  public void unsetIsFullOuterJoin() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ISFULLOUTERJOIN_ISSET_ID);
  }

  /** Returns true if field isFullOuterJoin is set (has been assigned a value) and false otherwise */
  public boolean isSetIsFullOuterJoin() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ISFULLOUTERJOIN_ISSET_ID);
  }

  public void setIsFullOuterJoinIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ISFULLOUTERJOIN_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
    switch (field) {
      case OFFSET:
        if (value == null) {
          unsetOffset();
        } else {
          setOffset((Long)value);
        }
        break;

      case SERIES_PATH:
        if (value == null) {
          unsetSeriesPath();
        } else {
          setSeriesPath((String)value);
        }
        break;

      case IS_CLOUD_EQUAL:
        if (value == null) {
          unsetIsCloudEqual();
        } else {
          setIsCloudEqual((Boolean)value);
        }
        break;

      case IS_INNER_JOIN:
        if (value == null) {
          unsetIsInnerJoin();
        } else {
          setIsInnerJoin((Boolean)value);
        }
        break;

      case IS_FULL_OUTER_JOIN:
        if (value == null) {
          unsetIsFullOuterJoin();
        } else {
          setIsFullOuterJoin((Boolean)value);
        }
        break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public Object getFieldValue(_Fields field) {
    switch (field) {
      case OFFSET:
        return getOffset();

      case SERIES_PATH:
        return getSeriesPath();

      case IS_CLOUD_EQUAL:
        return isIsCloudEqual();

      case IS_INNER_JOIN:
        return isIsInnerJoin();

      case IS_FULL_OUTER_JOIN:
        return isIsFullOuterJoin();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
      case OFFSET:
        return isSetOffset();
      case SERIES_PATH:
        return isSetSeriesPath();
      case IS_CLOUD_EQUAL:
        return isSetIsCloudEqual();
      case IS_INNER_JOIN:
        return isSetIsInnerJoin();
      case IS_FULL_OUTER_JOIN:
        return isSetIsFullOuterJoin();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that instanceof ScanInfo)
      return this.equals((ScanInfo)that);
    return false;
  }

  public boolean equals(ScanInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_offset = true;
    boolean that_present_offset = true;
    if (this_present_offset || that_present_offset) {
      if (!(this_present_offset && that_present_offset))
        return false;
      if (this.offset != that.offset)
        return false;
    }

    boolean this_present_seriesPath = true && this.isSetSeriesPath();
    boolean that_present_seriesPath = true && that.isSetSeriesPath();
    if (this_present_seriesPath || that_present_seriesPath) {
      if (!(this_present_seriesPath && that_present_seriesPath))
        return false;
      if (!this.seriesPath.equals(that.seriesPath))
        return false;
    }

    boolean this_present_isCloudEqual = true;
    boolean that_present_isCloudEqual = true;
    if (this_present_isCloudEqual || that_present_isCloudEqual) {
      if (!(this_present_isCloudEqual && that_present_isCloudEqual))
        return false;
      if (this.isCloudEqual != that.isCloudEqual)
        return false;
    }

    boolean this_present_isInnerJoin = true;
    boolean that_present_isInnerJoin = true;
    if (this_present_isInnerJoin || that_present_isInnerJoin) {
      if (!(this_present_isInnerJoin && that_present_isInnerJoin))
        return false;
      if (this.isInnerJoin != that.isInnerJoin)
        return false;
    }

    boolean this_present_isFullOuterJoin = true;
    boolean that_present_isFullOuterJoin = true;
    if (this_present_isFullOuterJoin || that_present_isFullOuterJoin) {
      if (!(this_present_isFullOuterJoin && that_present_isFullOuterJoin))
        return false;
      if (this.isFullOuterJoin != that.isFullOuterJoin)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(offset);

    hashCode = hashCode * 8191 + ((isSetSeriesPath()) ? 131071 : 524287);
    if (isSetSeriesPath())
      hashCode = hashCode * 8191 + seriesPath.hashCode();

    hashCode = hashCode * 8191 + ((isCloudEqual) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isInnerJoin) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isFullOuterJoin) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(ScanInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.compare(isSetOffset(), other.isSetOffset());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOffset()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.offset, other.offset);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.compare(isSetSeriesPath(), other.isSetSeriesPath());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSeriesPath()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.seriesPath, other.seriesPath);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.compare(isSetIsCloudEqual(), other.isSetIsCloudEqual());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsCloudEqual()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isCloudEqual, other.isCloudEqual);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.compare(isSetIsInnerJoin(), other.isSetIsInnerJoin());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsInnerJoin()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isInnerJoin, other.isInnerJoin);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.compare(isSetIsFullOuterJoin(), other.isSetIsFullOuterJoin());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsFullOuterJoin()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isFullOuterJoin, other.isFullOuterJoin);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ScanInfo(");
    boolean first = true;

    sb.append("offset:");
    sb.append(this.offset);
    first = false;
    if (!first) sb.append(", ");
    sb.append("seriesPath:");
    if (this.seriesPath == null) {
      sb.append("null");
    } else {
      sb.append(this.seriesPath);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("isCloudEqual:");
    sb.append(this.isCloudEqual);
    first = false;
    if (!first) sb.append(", ");
    sb.append("isInnerJoin:");
    sb.append(this.isInnerJoin);
    first = false;
    if (!first) sb.append(", ");
    sb.append("isFullOuterJoin:");
    sb.append(this.isFullOuterJoin);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ScanInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ScanInfoStandardScheme getScheme() {
      return new ScanInfoStandardScheme();
    }
  }

  private static class ScanInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<ScanInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ScanInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // OFFSET
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.offset = iprot.readI64();
              struct.setOffsetIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SERIES_PATH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.seriesPath = iprot.readString();
              struct.setSeriesPathIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // IS_CLOUD_EQUAL
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isCloudEqual = iprot.readBool();
              struct.setIsCloudEqualIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // IS_INNER_JOIN
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isInnerJoin = iprot.readBool();
              struct.setIsInnerJoinIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // IS_FULL_OUTER_JOIN
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isFullOuterJoin = iprot.readBool();
              struct.setIsFullOuterJoinIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ScanInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(OFFSET_FIELD_DESC);
      oprot.writeI64(struct.offset);
      oprot.writeFieldEnd();
      if (struct.seriesPath != null) {
        oprot.writeFieldBegin(SERIES_PATH_FIELD_DESC);
        oprot.writeString(struct.seriesPath);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(IS_CLOUD_EQUAL_FIELD_DESC);
      oprot.writeBool(struct.isCloudEqual);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(IS_INNER_JOIN_FIELD_DESC);
      oprot.writeBool(struct.isInnerJoin);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(IS_FULL_OUTER_JOIN_FIELD_DESC);
      oprot.writeBool(struct.isFullOuterJoin);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ScanInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ScanInfoTupleScheme getScheme() {
      return new ScanInfoTupleScheme();
    }
  }

  private static class ScanInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<ScanInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ScanInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetOffset()) {
        optionals.set(0);
      }
      if (struct.isSetSeriesPath()) {
        optionals.set(1);
      }
      if (struct.isSetIsCloudEqual()) {
        optionals.set(2);
      }
      if (struct.isSetIsInnerJoin()) {
        optionals.set(3);
      }
      if (struct.isSetIsFullOuterJoin()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetOffset()) {
        oprot.writeI64(struct.offset);
      }
      if (struct.isSetSeriesPath()) {
        oprot.writeString(struct.seriesPath);
      }
      if (struct.isSetIsCloudEqual()) {
        oprot.writeBool(struct.isCloudEqual);
      }
      if (struct.isSetIsInnerJoin()) {
        oprot.writeBool(struct.isInnerJoin);
      }
      if (struct.isSetIsFullOuterJoin()) {
        oprot.writeBool(struct.isFullOuterJoin);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ScanInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.offset = iprot.readI64();
        struct.setOffsetIsSet(true);
      }
      if (incoming.get(1)) {
        struct.seriesPath = iprot.readString();
        struct.setSeriesPathIsSet(true);
      }
      if (incoming.get(2)) {
        struct.isCloudEqual = iprot.readBool();
        struct.setIsCloudEqualIsSet(true);
      }
      if (incoming.get(3)) {
        struct.isInnerJoin = iprot.readBool();
        struct.setIsInnerJoinIsSet(true);
      }
      if (incoming.get(4)) {
        struct.isFullOuterJoin = iprot.readBool();
        struct.setIsFullOuterJoinIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

